# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Camp 2019"
description: "In this workshop we're going to build a Flask app that uses Azure Cognitive Services for text translation, sentiment analysis, and speech synthesis."
github_username:  erhopf

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
    "Demo: Cog Services Flask app":
      - "https://translator-tts-demo.azurewebsites.net/"
    "Full source code":
      - ""
